### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by forcegk**
Xabi vuelve de cenar ayudaaaaaaaaaaaa

### CODE REVIEW

**Comment by forcegk** [comment]
LGTM

**Comment by forcegk** [comment]
IÑAKI HOLAAAAAAAAAAAAAAAAAAAAAAA

**Comment by afdezfraga** [comment]
If Codee has million fans, then I'm one of them.
If Codee has one fan, then I'm THAT ONE.
If Codee has no fans, that means I'm dead.

**Comment by forcegk** [comment]
lol is that C++? Wait are you binding that with Python?! Imagine using those over Rust. As a proud Rustacean and Ferris the Crab adorer, I regret to inform you that your taste in languages sucks. This is sad. You can do better. You know how easy package and dependancy management is with Cargo? Not to mention you don’t even need a Makefile. It’s great. Dynamically typed languages need to die. There’s no other option. They just do. If you like dynamic typing, you need some help. Seriously. By using a dynamically typed and interpreted language (which means its @#*!&!@ slow!!!), you are committing genocide and harming the environment more than gas cars. Rust is fast and uses clean, renewable energy through the magic of being a language compiled with LLVM. Tired of memory bugs? You should be. Shame on you for still having them when Rust exists. Tired of being bad? Time to go to Rust. Tired of being slow because you’re not smart and your friends laugh at you? Rust is quite speedy indeed (all thanks to the big brain of the compiler). Tired of not getting off the normal way? Match statements, loops, and the compiler for Rust give the best orgasms 10/10 (completely legit). Not to mention the superiority you get to feel when you show off your superior Rust code to your inferior “friends” still using some other language. Want to get rid of malware? Rust is safe, therefore malware is noware (also completely legit). You quite honestly will forget about any other language (including English because it’s slow and unsafe). You even get to add the Rust Book and its brothers to your Bible collection alongside the Arch and Gentoo Wikis. All hail Rust. TempleOS pales in religious comparison to the faith of Rustaceans. Graydon Hoare is Jesus. Amen.

**Comment by forcegk** [comment]
> lol is that C++? Wait are you binding that with Python?! Imagine using those over Rust. As a proud Rustacean and Ferris the Crab adorer, I regret to inform you that your taste in languages sucks. This is sad. You can do better. You know how easy package and dependancy management is with Cargo? Not to mention you don’t even need a Makefile. It’s great. Dynamically typed languages need to die. There’s no other option. They just do. If you like dynamic typing, you need some help. Seriously. By using a dynamically typed and interpreted language (which means its @#*!&!@ slow!!!), you are committing genocide and harming the environment more than gas cars. Rust is fast and uses clean, renewable energy through the magic of being a language compiled with LLVM. Tired of memory bugs? You should be. Shame on you for still having them when Rust exists. Tired of being bad? Time to go to Rust. Tired of being slow because you’re not smart and your friends laugh at you? Rust is quite speedy indeed (all thanks to the big brain of the compiler). Tired of not getting off the normal way? Match statements, loops, and the compiler for Rust give the best orgasms 10/10 (completely legit). Not to mention the superiority you get to feel when you show off your superior Rust code to your inferior “friends” still using some other language. Want to get rid of malware? Rust is safe, therefore malware is noware (also completely legit). You quite honestly will forget about any other language (including English because it’s slow and unsafe). You even get to add the Rust Book and its brothers to your Bible collection alongside the Arch and Gentoo Wikis. All hail Rust. TempleOS pales in religious comparison to the faith of Rustaceans. Graydon Hoare is Jesus. Amen.

Convinced me. Merging.

**Comment by Erivos** [comment]
(Verse 1)
We're no strangers to code
You know the syntax and so do I (do I)
A full commit's what I'm thinking of
You wouldn't get this from any other byte
I just wanna debug and see you running
Gotta make you understand

(Chorus)
Never gonna pip install
Never gonna docker run
Never gonna Nginx serve and desert you
Never gonna SMTP fail
Never gonna raise exception
Never gonna tell a lie and hurt you

(Verse 2)
We've known each other in the Git log
Your script's been aching, but you're too shy to say it (say it)
Inside, we both know what's been going on (going on)
We know the code and we're gonna compile it
And if you ask me how I'm feeling
Don't tell me you're too blind to see

(Chorus)
Never gonna pip install
Never gonna docker run
Never gonna Nginx serve and desert you
Never gonna SMTP fail
Never gonna raise exception
Never gonna tell a lie and hurt you

(Bridge)
Never gonna import module
Never gonna docker pull
Never gonna Nginx reload and desert you
Never gonna SMTP timeout
Never gonna throw traceback
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Nunca vou correr e amatria-lo

**Comment by forcegk** [comment]
> (Verse 1) We're no strangers to code You know the syntax and so do I (do I) A full commit's what I'm thinking of You wouldn't get this from any other byte I just wanna debug and see you running Gotta make you understand
> 
> (Chorus) Never gonna pip install Never gonna docker run Never gonna Nginx serve and desert you Never gonna SMTP fail Never gonna raise exception Never gonna tell a lie and hurt you
> 
> (Verse 2) We've known each other in the Git log Your script's been aching, but you're too shy to say it (say it) Inside, we both know what's been going on (going on) We know the code and we're gonna compile it And if you ask me how I'm feeling Don't tell me you're too blind to see
> 
> (Chorus) Never gonna pip install Never gonna docker run Never gonna Nginx serve and desert you Never gonna SMTP fail Never gonna raise exception Never gonna tell a lie and hurt you
> 
> (Bridge) Never gonna import module Never gonna docker pull Never gonna Nginx reload and desert you Never gonna SMTP timeout Never gonna throw traceback Never gonna tell a lie and hurt you Never gonna give you up Never gonna let you down Nunca vou correr e amatria-lo


pic

**Pull request merged**
